export const ActionTypes = {
  //AUTH
  AUTHENTICATED_USER: "AUTHENTICATED_USER",
  LOGOUT_USER: "LOGOUT_USER",
  EXPLOYERS_LIST: "EXPLOYERS_LIST",

  JOBS_LIST: "JOBS_LIST",
  JOB: "JOB"
  
};
